### ISSUE TITLE
Null Voices Cause iPhone to crash

### ISSUE THREAD

**Issue by mattvv** [mattvv/lineplease#50]
Thank you to Arlene for finding this one!

If the voice is incorrectly set - when playing a Line iOS crashes.
The workaround for this at the moment is to hard set each line to have a voice. (I did this for teresas case).

I will have a fix in for this in the next iOS (1.1.4) version.
The problem is at the gender check in Speaker.m line 124

**Comment by larobert** [comment]
Maybe I am not understanding what a "hard set" is.  But, each line input has the approperiate male or female gender set.

**Comment by mattvv** [comment]
Fixed in 1.1.4 - This is submitted to the App store waiting approval

**Comment by larobert** [comment]
Thanks for the update!
