### ISSUE TITLE
Link Facebook login with registered account

### ISSUE THREAD

**Issue by gabespc** [mattvv/lineplease#58]
I signed in with Facebook to start with, and began creating my script.
Then I realized the FB login took longer on my iPhone, so I created an account on the website to log in with.
It's much faster than the FB login, but my script I began isn't there. It's still there on the Facebook login, but I see no way to move, copy, export or link it to my registered account.

**Comment by mattvv** [comment]
@gabespc - If you give me the title of your script I can move it to your new account as long as you give me the new account name :)

Thanks,
Matt

**Comment by gabespc** [comment]
The account name should be gabespc.
Thanks! :)

**Comment by mattvv** [comment]
Thanks @gabespc - Can you also provide me with the name of the script that is on the other account.

**Comment by gabespc** [comment]
Oops! It's "Damn Yankees".

**Comment by mattvv** [comment]
I moved this script to your gabespc account :) Please let me know if this all works and close this ticket if you're satisfied :)

Thanks,

Matt

**Comment by gabespc** [comment]
Worked great! Thanks so much for your help & keep up the great work on the app!
