### ISSUE TITLE
iPhone app crashes after editing a line.

### ISSUE THREAD

**Issue by gabespc** [mattvv/lineplease#61]
When you swipe a line and tap Edit, the edit Window opens and you can make your changes, but when you press Save, the app disappears and you have to restart it, log in again and the edit was not saved.

I asked other players and their phones do the same thing, so it's not isolated to my device.

**Comment by mattvv** [comment]
Thanks @gabespc i'll try and take a look at this tonight for you :)

**Comment by mattvv** [comment]
This is fixed in 1.1.7. Which is currently on its way to the app store.
