### ISSUE TITLE
No visible cursor on iPhone

### ISSUE THREAD

**Issue by gabespc** [mattvv/lineplease#62]
When entering a new Line or Character name, there is no | cursor symbol  on the iphone.
If you hold to magnify/move the cursor, you can't tell where you are placing it. It DOES move your position, but you can't tell where you are until you start typing and see the new text appear.

Somewhat related - if you misspell a word and it's underlined in red, if you try to move your position back to it, it deletes the whole word.

**Comment by mattvv** [comment]
Fixed in 1.1.7
