### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by danielwill** [mattvv/lineplease#63]
I'm running an iPhone 3Gs with iOS 4.3.2 and LinePlease displays the splash screen, then crashes, with no explanation.

I tried deleting and re-installing and got the same results.

I really want to use this software, but it simply won't run on my iPhone.

Any suggestions?

Thanks!

Daniel

**Comment by mattvv** [comment]
Hi Daniel, Thanks for posting this!

I'm going to take a look at this today and see if I can reproduce on an iPhone 3GS with iOS 4. Hopefully i'll be able to provide a fix for you!

**Comment by mattvv** [comment]
I've fixed a crash on load issue in 1.1.7. Unfortuantely I can't test it on iOS 4 as apple has removed access to the iOS 4 simulator. Let me know how this goes when 1.1.7 hits the app store.
