### ISSUE TITLE
resetting password and other questions... 

### ISSUE THREAD

**Issue by mollyodailey** [mattvv/lineplease#70]
Hi, I was trying to reset my password and keep getting a 'failed  to reset password' error.

Additionally, when entering a scene does it top out at a hundred 'lines'?  I was reading another post and am guessing that is why it stopped accepting lines for the scene I was entering but figured I would ask.

Thanks for creating such a handy tool!  I plan on sharing it with the rest of my cast at rehearsal tonight!

**Comment by mattvv** [comment]
Please test now, issues should be resolved :)
