### ISSUE TITLE
The app won't save

### ISSUE THREAD

**Issue by aeon815** [mattvv/lineplease#86]
Every time I write in a new line and save it, it says "could not save" and that's it. I tried deleting the app and re-downloading, but the same issue. I tried deleting the script and adding a new one and entering lines. Same problem. Any fixes?

**Comment by aeon815** [comment]
I'm on an iPhone 4... it worked about a month ago and now it does the above.

**Comment by mattvv** [comment]
@aeon815 - Thanks for reporting this, we made some changes on the server side. Please see if this works now.
